apiVersion: v1
kind: ReplicationController
metadata:
  name: monitoring-heapster-v5
  namespace: default
  labels:
    k8s-app: heapster
    version: v5
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: v5
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v5
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
        - image: gcr.io/google_containers/heapster:v0.15.0
          name: heapster
          command:
            - /heapster
            - --source=kubernetes:''
