kind: PersistentVolume
apiVersion: v1beta3
metadata:
  name: pv0003
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  gcePersistentDisk:
    pdName: "abc123"
    fsType: "ext4"
